### ISSUE TITLE
A error when lede make

### ISSUE THREAD

**Issue by HashimotoSakura** [solidus1983/luci-theme-opentomato#7]
when use `make menuconfig` can get an error :
`Makefile:12: ../../luci.mk: No such file or directory
make[2]: *** No rule to make target '../../luci.mk'.  Stop.
`

how about change `../../luci.mk` to `
include $(TOPDIR)/feeds/luci/luci.mk
` in make file ?

**Comment by solidus1983** [comment]
which version of LEDE are you building it against ?

**Comment by solidus1983** [comment]
Made changes, give it another git pull and see if it works.
