### ISSUE TITLE
请问，如果是官方openwrt编译的话，这个主题要怎么放到目录里去啊？

### ISSUE THREAD

**Issue by aotuitx** [solidus1983/luci-theme-opentomato#8]
我直接拉取 ../luci/themes/luci-theme-opentomato 目录放到package里的话，生成主题后一直显示正在获取信息。

**Comment by solidus1983** [comment]
Not sure if this is translated correctly but what your saying


`If I directly pull the ../luci/themes/luci-theme-opentomato directory and put it in the package, it keeps showing that it is getting information after the theme is generated.`

Your meant to pull the whole git repo as in

`git clone https://github.com/solidus1983/luci-theme-opentomato.git`

or the better way is to add the repo to the feeds.conf.default of OpenWRT so it looks something like

`src-git opentomato https://github.com/solidus1983/luci-theme-opentomato.git`

**Comment by aotuitx** [comment]
> 不确定翻译是否正确，但您说什么
> 
> > 如果我直接拉../luci/themes/luci-theme-opentomato目录并将其放在包中，它会不断显示它在生成主题之后正在获取信息。
> 
> 您打算像这样拉整个git repo
> 
> `git clone https://github.com/solidus1983/luci-theme-opentomato.git`
> 
> 或者更好的方法是将仓库添加到OpenWRT的feeds.conf.default中，使其看起来像
> 
> `src-git opentomato https://github.com/solidus1983/luci-theme-opentomato.git`

thank you
