### ISSUE TITLE
Hello, here I am again, I prefer this theme, but he can't use it when https://github.com/coolsnowwolf/lede compile. Please ask how to solve this problem.

### ISSUE THREAD

**Issue by aotuitx** [solidus1983/luci-theme-opentomato#9]
Hello, here I am again, I prefer this theme, but he can't use it when https://github.com/coolsnowwolf/lede compile.
Please ask how to solve this problem.

**Comment by solidus1983** [comment]
You do know that this is based on OpenWRT Master branch right which LUCI had a theme upgrade, which this theme was patched to.

I don't personally use LEDE so do not know how its LUCI is patched.

However there is a better theme to this one https://github.com/jerrykuku/luci-theme-argon which is what i have started to use myself along with https://github.com/jerrykuku/luci-app-argon-config . give it a shot.

**Comment by aotuitx** [comment]
Thanks
